apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: carts-route
spec:
  parentRefs:
    - name: gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/api/carts"
      backendRefs:
        - name: carts-svc
          namespace: services
          port: 8080
