apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
   name: fulfillment-route
   namespace: services
spec:
   parentRefs:
      - name: gateway
        namespace: envoy-gateway-system
   rules:
      - matches:
           - path:
                type: PathPrefix
                value: /api/fulfillment
        backendRefs:
           - name: fulfillment-svc
             port: 8080
