apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
   name: vouchers-route
spec:
   parentRefs:
      - name: gateway
   rules:
      - matches:
           - path:
                type: PathPrefix
                value: /api/vouchers
        backendRefs:
           - name: vouchers-svc
             namespace: services
             port: 8080
