apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
   name: debezium-connector-order-placement-pg-outbox
   namespace: kafka
   labels:
      strimzi.io/cluster: debezium-connect-cluster
spec:
   class: io.debezium.connector.postgresql.PostgresConnector
   tasksMax: 1
   autoRestart:
      enabled: true
   config:
      tasks.max: 1
      database.hostname: order-placement-pg-db.storages
      database.port: 5432
      database.user: postgres
      database.password: postgres
      database.server.id: 184054
      topic.prefix: order-placement-pg-
      database.dbname: mydatabase
      plugin.name: pgoutput
      # database.include.list: mydatabase
      table.include.list: public.outboxes
      schema.history.internal.kafka.bootstrap.servers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      schema.history.internal.kafka.topic: schema-changes.outbox