apiVersion: apps/v1
kind: Deployment
metadata:
   name: product-categories-service
   namespace: services
   labels:
      app: product-categories
spec:
   replicas: 1
   selector:
      matchLabels:
         app: product-categories
   template:
      metadata:
         labels:
            app: product-categories
      spec:
         containers:
            - name: product-categories
              image: rengumin/product-categories-svc:1.0
              ports:
                 - containerPort: 8080
              env:
                 - name: DB_HOST
                   value: product-categories-pg-db.storages
                 - name: DB_PORT
                   value: "5432"
                 - name: DB_USER
                   value: postgres
                 - name: DB_PASSWORD
                   value: postgres
                 - name: DB_NAME
                   value: mydatabase
              resources:
                 requests:
                    cpu: "250m"
                    memory: "128Mi"
                 limits:
                    cpu: "500m"
                    memory: "1G"
---
apiVersion: v1
kind: Service
metadata:
   name: product-categories-svc
   namespace: services
spec:
   type: ClusterIP
   selector:
      app: product-categories
   ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
