apiVersion: apps/v1
kind: Deployment
metadata:
   name: vouchers-service
   namespace: services
spec:
   replicas: 1
   selector:
      matchLabels:
         app: vouchers
   template:
      metadata:
         labels:
            app: vouchers
      spec:
         containers:
            - name: vouchers
              image: rengumin/vouchers-svc:1.0
              ports:
                 - containerPort: 8080
              env:
                 - name: DB_HOST
                   value: "vouchers-pg-db.storages"
                 - name: DB_PORT
                   value: "5432"
                 - name: DB_USER
                   value: postgres
                 - name: DB_PASSWORD
                   value: postgres
                 - name: DB_NAME
                   value: mydatabase
                 - name: SERVER_PORT
                   value: "8080"
              resources:
                 requests:
                    cpu: "500m"
                    memory: "256Mi"
                 limits:
                    cpu: "1"
                    memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
   name: vouchers-svc
   namespace: services
spec:
   type: ClusterIP
   selector:
      app: vouchers
   ports:
      - protocol: TCP
        name: http
        port: 8080
        targetPort: 8080
      - protocol: TCP
        name: grpc
        port: 50050
        targetPort: 50050
